ALTER TABLE traveller ADD status VARCHAR(256) NOT NULL DEFAULT('');
ALTER TABLE traveller DROP COLUMN signature;

-- 创建账号
DROP TABLE ACCOUNT;
CREATE TABLE ACCOUNT(
    ID BIGINT NOT NULL,
    NAME VARCHAR(36) NOT NULL,
    SALT VARCHAR(256) NOT NULL,
    CREATE_TIME DATETIME NOT NULL,
    SECRET VARCHAR(256) NOT NULL,
    STATUS INT NOT NULL,
    EXPIRED_TIME TIMESTAMP DEFAULT '2000-1-1 0:00:00' NOT NULL
)

-- 创建账号激活码
CREATE TABLE account_activation(
    id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    user_code VARCHAR(256) NOT NULL,
    CREATE_TIME DATETIME NOT NULL,
    EXPIRED_TIME TIMESTAMP DEFAULT '2000-1-1 0:00:00' NOT NULL
)