# actuator config
management:
  endpoint.health.show-details: always
  endpoints:
    web.exposure.include: prometheus,loggers
    metrics.export.prometheus.enabled: true
  metrics:
    tags.application: jazzy

# spring config
spring:
  port: 8080
  shutdown: graceful
  error:
    include-stacktrace: NEVER
    include-exception: false

  datasource:
    url: jdbc:mysql://101.200.53.244:3306/jazzy?useSSL=false&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Wu5%AVGr
    driver-class-name: com.mysql.jdbc.Driver
    hikari.maximum-pool-size: 2

  # 发送邮件配置
  mail:
    user-name: jimmymzhang@163.com
    password: 43z58j70m36~
    host: smtp.163.com
    port: 465
    properties:
      mail.smtp.user: jimmymzhang@163.com
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

  # cache config
  cache:
    # type: REDIS
    type: CAFFEINE
    caffeine:
      spec: initialCapacity=2,maximumSize=200,expireAfterWrite=10m,recordStats

  # redis config
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

# global config
summer:
  http-config:
    cache-max-age: 3600
    cors-allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  jwt-config:
    token-expired: 30D
    token-secret: 7p9izREdj3cAAQR7HyDCoMDv9dDDtzQLbJ1ScicADAclc
    token-subject: jazzy
    token-issue: cove
    token-claim: id
  cache-config:
    null-duration-time: 1
  redis-config:
    duration-time: 60
  security-config:
    permit-urls: /error,/user/**
  system-config:
    run-time: PRODUCTION
