# spring config
spring:
  datasource:
    url: jdbc:mysql://101.200.53.244:3306/jazzy?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
    username: root
    password: Wu5%AVGr
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari.maximum-pool-size: 2
    hikari.registerMbeans: true

  # cache config
  cache:
    type: CAFFEINE
    caffeine:
      spec: initialCapacity=2,maximumSize=200,expireAfterWrite=10m,recordStats

# global config
summer:
  system-config:
    run-time: DEVELOPMENT
