# server info
server:
  port: 8080

# spring config
spring:
  # profile config
  profiles:
    active: "@profile.active@"

  # cache config
  cache:
    type: SIMPLE

  # servlet config
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1KB
      max-file-size: 10MB
      max-request-size: 20MB

# logging config
logging:
  config: classpath:log4j-config.xml

# mybatis config
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: plus.cove.jazzy.domain.*

mapper:
  identity: MYSQL
  enum-as-simple-type: true

# global config
summer:
  http-config:
    cache-max-age: 3600
    cors-allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  jwt-config:
    token-expired: 7d
    token-secret: 7p9izREdj3cAAQR7HyDCoMDv9dDDtzQLbJ1ScicADAclc
    token-subject: jazzy
    token-issue: cove
    token-claim: id
  cache-config:
    null-duration-time: 1
    duration-time: 60
  json-config:
    datetime-format: yyyy-MM-dd HH:mm:ss
  security-config:
    permit-urls: /error
  system-config:
    run-time: DEVELOPMENT

