# actuator config
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,trace

# spring config
spring:
  port: 8080
  error:
    include-stacktrace: NEVER
    include-exception: false

  datasource:
    url: jdbc:mysql://101.200.53.244:3306/jazzy?useSSL=false&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf-8
    user-name: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari.maximum-pool-size: 12

  # cache config
  cache:
    type: SIMPLE

  # 发送邮件配置
  mail:
    user-name: jimmymzhang@163.com
    password: 43z58j70m36~
    host: smtp.163.com
    port: 465
    properties:
      mail.smtp.user: jimmymzhang@163.com
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

# global config
summer:
  http-config:
    cache-max-age: 3600
    cors-allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  jwt-config:
    token-expired: 10080
    token-secret: 7p9izREdj3cAAQR7HyDCoMDv9dDDtzQLbJ1ScicADAclc
    token-subject: jazzy
    token-issue: cove
    token-claim: id
  cache-config:
    null-duration-time: 1
  redis-config:
    duration-time: 60
  system-config:
    run-time: PRODUCTION
