# spring config
spring:
  # datasource config
  datasource:
    url: jdbc:sqlite:c:/users/jimmy/cove.db
    driver-class-name: org.sqlite.JDBC
    user-name:
    password:

  # cache config
  cache:
    type: REDIS

  redis:
    host: 127.0.0.1
    port: 6379