# server info
server:
  port: 8080

# spring config
spring:
  # profile config
  profiles:
    active: "develop"

  # servlet config
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1KB
      max-file-size: 10MB
      max-request-size: 20MB

  # 发送邮件配置
  mail:
    user-name: jimmymzhang@163.com
    password: 43z58j70m36~
    host: smtp.163.com
    port: 465
    properties:
      mail.smtp.user: jimmymzhang@163.com
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

# logging config
logging:
  path: logs
  file:
    # 最少保留15天，防止某些异常以周为频次发生
    max-history: 15
    max-size: 20MB

# mybatis-plus config
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-enums-package: plus.cove.jazzy.domain.*
  type-aliases-package: plus.cove.jazzy.domain.*
  type-handlers-package: plus.cove.infrastructure.mybatis
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
  global-config:
    super-mapper-class: plus.cove.infrastructure.component.BaseRepository

# global config
summer:
  http-config:
    cache-max-age: 3600
    cors-allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  jwt-config:
    token-expired: 10080
    token-secret: 7p9izREdj3cAAQR7HyDCoMDv9dDDtzQLbJ1ScicADAclc
    token-subject: jazzy
    token-issue: cove
    token-claim: id
  redis-config:
    expired-minutes: 60
  json-config:
    datetime-format: yyyy-MM-dd HH:mm
  security-config:
    permit-urls: /error
  system-config:
    run-time: DEVELOPMENT

# project config
autumn:
  account-activation:
    active-days: 7
    active-url: localhost:8080/active.html?code=

