# server info
server:
  port: 8080

# spring config
spring:
  datasource:
    url: jdbc:h2:/usr/local/cove/data/cove;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE;MODE=MySql;MVCC=TRUE
    driver-class-name: org.h2.Driver
    user-name: root
    password: root

  # servlet config
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1KB
      max-file-size: 10MB
      max-request-size: 20MB

# logging config
logging:
  path: ../logs
  file:
    max-history: 15
    max-size: 20MB

# global config
summer:
  http-config:
    cache-max-age: 3600
    cors-allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  jwt-config:
    token-expired: 10080
    token-secret: 7p9izREdj3cAAQR7HyDCoMDv9dDDtzQLbJ1ScicADAclc
    token-subject: cove
    token-issue: carbybus
    token-claim: id
  redis-config:
    expired-minutes: 0
  upload-config:
    upload-path: /usr/local/cove/uploads

# project config
autumn:
  account-activation:
    active-days: 7
    active-url: http://www.gotravelling.top/user/active?code=