# actuator config
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,trace

# spring config
spring:
  port: 8080
  error:
    include-stacktrace: NEVER
    include-exception: false

  datasource:
    url: jdbc:sqlite:/usr/local/cove/data/cove.db
    driver-class-name: org.sqlite.JDBC
    user-name:
    password:

  # cache config
  cache:
    type: SIMPLE

  # 发送邮件配置
  mail:
    user-name: jimmymzhang@163.com
    password: 43z58j70m36~
    host: smtp.163.com
    port: 465
    properties:
      mail.smtp.user: jimmymzhang@163.com
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

# global config
summer:
  http-config:
    cache-max-age: 3600
    cors-allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  jwt-config:
    token-expired: 10080
    token-secret: 7p9izREdj3cAAQR7HyDCoMDv9dDDtzQLbJ1ScicADAclc
    token-subject: jazzy
    token-issue: cove
    token-claim: id
  cache-config:
    null-duration-time: 1
  redis-config:
    duration-time: 60
  json-config:
    datetime-format: yyyy-MM-dd HH:mm:ss
  security-config:
    permit-urls: /error
  system-config:
    run-time: PRODUCTION

# project config
autumn:
  account-activation:
    active-days: 7
    active-url: localhost:8080/active.html?code=