# server info
server:
  port: 8080

# spring config
spring:
  # profile config
  profiles:
    active: "@profile.active@"

  # cache config
  cache:
    type: redis
    redis:
      key-prefix: COVE

  # redis config
  redis:
    host: 127.0.0.1
    port: 6379

  # servlet config
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1KB
      max-file-size: 10MB
      max-request-size: 20MB
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
        trace: true

# logging config
logging:
  path: logs
  file:
    max-history: 15
    max-size: 20MB

# mybatis-plus config
mybatis-plus:
  config-lacation: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
  type-enums-package: com.carbybus.cove.domain.*
  type-aliases-package: com.carbybus.cove.domain.*
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.EnumTypeHandler
  global-config:
    super-mapper-class: com.carbybus.infrastructure.component.BaseRepository

# global config
summer:
  http-config:
    cache-max-age: 3600
    cors-allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  jwt-config:
    token-expired: 10080
    token-secret: 7p9izREdj3cAAQR7HyDCoMDv9dDDtzQLbJ1ScicADAclc
    token-subject: Traveller
    token-issue: carbybus
    token-claim: id
  redis-config:
    expired-minutes: 0
  email-config:
    host-name: smtp.163.com
    host-port: 465
    ssl-connect: true
    from-user: jimmymzhang@163.com
    user-name: jimmymzhang@163.com
    user-password: 43z58j70m36~

