# actuator config
management:
  endpoints:
    web.exposure.include: health,info,metrics,loggers,prometheus
  endpoint:
    health.show-details: always

# spring config
spring:
  datasource:
    url: jdbc:mysql://101.200.53.244:3306/cove?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
    username: root
    password: Wu5%AVGr
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari.maximum-pool-size: 12
    hikari.registerMbeans: true

  # cache config
  cache:
    type: SIMPLE

  redis:
    host: 127.0.0.1
    port: 6379

# global config
summer:
  upload-config:
    upload-path: /usr/local/cove
  system-config:
    run-time: DEVELOPMENT

# project config
autumn:
  account-activation:
    active-days: 7
    active-url: http://cloud.gongzuolai.com/active.html?code=