# server info
server:
  port: 8088

# spring datasource config
spring:
  datasource:
    url: jdbc:mysql://192.168.168.40:3307/cove_business?useSSL=false&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf-8
    user-name: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # mysql configuration
    useServerPrepStmts: true
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useLocalSessionState: true
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false

# logging config
logging:
  path: logs
  file:
    max-history: 15
    max-size: 20MB
  level.org: warn

summer:
  http-config:
    cache-max-age: 600
    cors-allowed-origins: http://www.carbybus.com
    cors-allowed-headers: GET,POST,PUT,DELETE