# spring config
spring:
  # datasource config
  datasource:
    url: jdbc:sqlite:c:/users/jimmy/cove.db
    driver-class-name: org.sqlite.SQLiteDataSource
    user-name:
    password:

  # cache config
  cache:
    type: SIMPLE