# spring config
spring:
  datasource:
    url: jdbc:mysql://192.168.168.40:3307/cove_business?useSSL=false&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf-8
    user-name: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # mysql configuration
    useServerPrepStmts: true
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useLocalSessionState: true
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false

  # redis config
  redis:
    host: 127.0.0.1
    port: 6379
