# actuator config
management:
  endpoints:
    web.exposure.include: health,info,metrics,loggers,httptrace
  endpoint:
    health.show-details: always

# spring config
spring:
  datasource:
    url: jdbc:mysql://101.200.53.244:3306/cove?useSSL=false&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Wu5%AVGr
    driver-class-name: com.mysql.jdbc.Driver

  # cache config
  cache:
    type: SIMPLE

  redis:
    host: 127.0.0.1
    port: 6379