# server info
server:
  port: 8088

# spring config
spring:
  profiles:
    active: "@profile.active@"
  cache:
    type: Redis
    redis:
      key-prefix: COVE
  redis:
    host: 127.0.0.1
    port: 6379

# logging config
logging:
  path: logs
  file:
    max-history: 15
    max-size: 20MB

# mybatis-plus config
mybatis-plus:
  config-lacation: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
  type-enums-package: com.carbybus.cove.domain.*
  type-aliases-package: com.carbybus.cove.domain.*
  global-config:
    super-mapper-class: com.carbybus.infrastructure.component.BaseRepository

# global config
summer:
  http-config:
    cache-max-age: 600
    cors-allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    cors-allowed-headers: Authorization
  jwt-config:
    token-expired: 10080
    token-secret: 7p9izREdj3cAAQR7HyDCoMDv9dDDtzQLbJ1ScicADAclc
    token-subject: user
    token-issue: carbybus
    token-claim: id
