# actuator config
management:
  endpoints:
    web.exposure.include: health,info,metrics,loggers,httptrace
  endpoint:
    health.show-details: always

# spring config
spring:
  datasource:
    url: jdbc:mysql://192.168.168.40:3307/cove_business?useSSL=false&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf-8
    user-name: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  # cache config
  cache:
    type: SIMPLE

  redis:
    host: 127.0.0.1
    port: 6379