# spring config
spring:
  datasource:
    url: jdbc:sqlite:/usr/local/cove/data/cove.db
    driver-class-name: org.sqlite.JDBC
    user-name:
    password:

  # cache config
  cache:
    type: SIMPLE

  # 发送邮件配置
  mail:
    user-name: jimmymzhang@163.com
    password: 43z58j70m36~
    host: smtp.163.com
    port: 465
    properties:
      mail.smtp.user: jimmymzhang@163.com
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

# logging config
logging:
  path: ../logs
  file:
    max-history: 15
    max-size: 20MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,trace

# global config
summer:
  http-config:
    cache-max-age: 3600
    cors-allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  jwt-config:
    token-expired: 10080
    token-secret: 7p9izREdj3cAAQR7HyDCoMDv9dDDtzQLbJ1ScicADAclc
    token-subject: travel
    token-issue: jimmy
    token-claim: id
  redis-config:
    expired-minutes: 43200
  upload-config:
    upload-path: /usr/local/cove/uploads

# project config
autumn:
  account-activation:
    active-days: 7
    active-url: http://www.gotravelling.top/active.html?code=